apiVersion: volumesnapshot.external-storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: prod-db-snapshots
  namespace: default
  annotations:
    portworx/snapshot-type: local
    portworx/tier: prod
    portworx/type: db
spec:
  persistentVolumeClaimName: wp-pv-claim